### ISSUE TITLE
S2R cyrillic omits first letter when capitalize is on

### ISSUE THREAD

**Issue by scossu** [lcnetdev/scriptshifter#121]
Wen `capitailze="first"` or `capitalize="all"`, all first letters of every word after the first are omitted from transliteration. in several Cyrillic languages., including Russian, Belarusian, and Ukrainian.

E.g.

```
In [12]: transliterate('abc def ghi', "russian", t_dir="r2s", capitalize="first")
INFO:scriptshifter.trans:Transliteration is from Latin to russian.
INFO:scriptshifter.trans:Loaded table for russian.
DEBUG:scriptshifter.trans:Beginning of word at position 0.
INFO:scriptshifter.trans:Capitalizing token.
DEBUG:scriptshifter.trans:End of word at position 2.
DEBUG:scriptshifter.trans:d is after c. Breaking loop.
INFO:scriptshifter.trans:Token c (\u63) at position 2 is not mapped.
INFO:scriptshifter.trans:Ignored token:  
DEBUG:scriptshifter.trans:' is after d. Breaking loop.
INFO:scriptshifter.trans:Token   (\u20) at position 4 is not mapped.
DEBUG:scriptshifter.trans:End of word at position 6.
INFO:scriptshifter.trans:Ignored token:  
DEBUG:scriptshifter.trans:' is after g. Breaking loop.
INFO:scriptshifter.trans:Token   (\u20) at position 8 is not mapped.
DEBUG:scriptshifter.trans:ī is after hi. Breaking loop.
INFO:scriptshifter.trans:Token h (\u68) at position 9 is not mapped.
DEBUG:scriptshifter.trans:End of word at position 10.
DEBUG:scriptshifter.trans:Output list: ['А', 'б', 'c', ' ', ' ', 'е', 'ф', ' ', ' ', 'h', 'и']
Out[12]: ('Абc еф hи', [])
```
Note that the first letter of the second word is actually transliterated as a space (then collapsed to one in further processing).

**Comment by scossu** [comment]
This is a more widespread problem with R2S and is not affected by capitalization: 

```
[ins] In [6]: transliterate('abk dey gsi', "greek_modern", t_dir="r2s")
INFO:scriptshifter.trans:Transliteration is from Latin to greek_modern.
INFO:scriptshifter.trans:Loaded table for greek_modern.
DEBUG:scriptshifter.trans:Beginning of word at position 0.
DEBUG:scriptshifter.trans:End of word at position 2.
INFO:scriptshifter.trans:Ignored token:  
DEBUG:scriptshifter.trans:"̲ is after de. Breaking loop.
INFO:scriptshifter.trans:Token   (\u20) at position 4 is not mapped.
DEBUG:scriptshifter.trans:End of word at position 6.
INFO:scriptshifter.trans:Ignored token:  
DEBUG:scriptshifter.trans:"̲ is after gs. Breaking loop.
INFO:scriptshifter.trans:Token   (\u20) at position 8 is not mapped.
DEBUG:scriptshifter.trans:End of word at position 10.
DEBUG:scriptshifter.trans:Output list: ['α', 'β', 'κ', ' ', ' ', 'ε', 'υ', ' ', ' ', 'σ', 'ι']
Out[6]: ('αβκ ευ σι', [])```

**Comment by scossu** [comment]
Fixed in [ed5a8e5](https://github.com/lcnetdev/scriptshifter/commit/ed5a8e5353bb37971bb05ff163bae87d3df54445).

**Comment by quinnka2** [comment]
I still see the problem. 

Original: Здравствуйте, меня зовут Келли

Transliterated script to Roman to: Zdravstvuĭte, meni︠a︡ zovut Kelli.


Zdravstvuĭte, meni︠a︡ zovut Kelli.

Transliterated Roman to script to: Здравствуйте, еня овут елли. Missing the м, з, and К.
